-- Buckets database schema

create extension if not exists "uuid-ossp";

create table if not exists profiles (
  id uuid primary key references auth.users(id),
  display_name text not null,
  role text not null default 'viewer' check (role in ('viewer','admin','owner')),
  created_at timestamptz not null default now()
);

create table if not exists players (
  player_id bigint generated by default as identity primary key,
  name text not null,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists tiers (
  tier_id smallint generated by default as identity primary key,
  tier_name text unique not null,
  color text not null,
  created_at timestamptz not null default now()
);

create table if not exists seasons (
  season_id bigint generated by default as identity primary key,
  season_name text not null,
  status text not null check (status in ('planned','active','completed','cancelled')),
  start_at timestamptz,
  end_at timestamptz,
  created_by uuid references profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists season_teams (
  season_team_id bigint generated by default as identity primary key,
  season_id bigint not null references seasons(season_id) on delete cascade,
  team_name text not null,
  sort_order int,
  unique (season_id, team_name)
);

create table if not exists season_roster (
  season_roster_id bigint generated by default as identity primary key,
  season_id bigint not null references seasons(season_id) on delete cascade,
  player_id bigint not null references players(player_id),
  season_team_id bigint references season_teams(season_team_id),
  tier_id smallint references tiers(tier_id),
  shot_limit int,
  manual_points_override int,
  manual_shots_remaining_override int,
  is_active boolean not null default true,
  unique (season_id, player_id)
);

create table if not exists shot_events (
  shot_id bigint generated by default as identity primary key,
  season_id bigint not null references seasons(season_id) on delete cascade,
  season_roster_id bigint not null references season_roster(season_roster_id) on delete cascade,
  taken_at timestamptz not null default now(),
  base_value smallint not null check (base_value in (0,1,2)),
  multiplier smallint not null check (multiplier in (1,2)),
  shot_index int not null,
  is_voided boolean not null default false,
  points int not null check (points in (0,1,2,4,8)),
  recorded_by uuid references profiles(id),
  note text,
  unique (season_roster_id, shot_index)
);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from profiles p
    where p.id = auth.uid()
      and p.role in ('admin','owner')
  );
$$;

grant execute on function public.is_admin() to public;

create or replace function public.record_shot(
  p_season_roster_id bigint,
  p_base_value smallint,
  p_multiplier smallint,
  p_note text default null
) returns shot_events
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season_id bigint;
  v_shot_index int;
  v_moneyball_multiplier smallint := 1;
  v_points int;
  v_row shot_events;
begin
  select sr.season_id into v_season_id
  from season_roster sr
  join seasons s on s.season_id = sr.season_id
  where sr.season_roster_id = p_season_roster_id
    and s.status = 'active'
  limit 1;

  if v_season_id is null then
    raise exception 'Season roster not in active season';
  end if;

  select coalesce(max(shot_index), 0) + 1 into v_shot_index
  from shot_events
  where season_roster_id = p_season_roster_id;

  if mod(v_shot_index, 10) = 0 then
    v_moneyball_multiplier := 2;
  end if;

  v_points := p_base_value * p_multiplier * v_moneyball_multiplier;

  insert into shot_events (
    season_id,
    season_roster_id,
    base_value,
    multiplier,
    shot_index,
    points,
    note,
    recorded_by
  )
  values (
    v_season_id,
    p_season_roster_id,
    p_base_value,
    p_multiplier,
    v_shot_index,
    v_points,
    p_note,
    auth.uid()
  )
  returning * into v_row;

  return v_row;
end;
$$;

grant execute on function public.record_shot to public;

create or replace function public.void_shot(
  p_shot_id bigint,
  p_reason text default null
) returns shot_events
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row shot_events;
begin
  if not is_admin() then
    raise exception 'Only admins may void shots';
  end if;

  update shot_events
  set is_voided = true,
      note = coalesce(note, '') || coalesce(' (void: ' || p_reason || ')', '')
  where shot_id = p_shot_id
  returning * into v_row;

  return v_row;
end;
$$;

grant execute on function public.void_shot to public;

create or replace view public.v_active_scoreboard_rows as
with active_seasons as (
  select season_id from seasons where status = 'active'
),
shot_totals as (
  select
    sr.season_roster_id,
    coalesce(sum(se.points) filter (where se.is_voided = false), 0) as earned_points,
    coalesce(count(se.*) filter (where se.is_voided = false), 0) as shots_taken
  from season_roster sr
  left join shot_events se on se.season_roster_id = sr.season_roster_id
  group by sr.season_roster_id
),
roster_with_points as (
  select
    sr.season_id,
    sr.season_team_id,
    st.team_name,
    sr.player_id,
    p.name as player_name,
    coalesce(sr.manual_points_override, stot.earned_points) as player_points,
    stot.shots_taken
  from season_roster sr
  join active_seasons a on a.season_id = sr.season_id
  join players p on p.player_id = sr.player_id
  left join season_teams st on st.season_team_id = sr.season_team_id
  left join shot_totals stot on stot.season_roster_id = sr.season_roster_id
  where sr.is_active = true
),
team_totals as (
  select season_id, season_team_id, sum(player_points) as team_points
  from roster_with_points
  group by season_id, season_team_id
)
select
  rwp.season_id,
  rwp.season_team_id,
  rwp.team_name,
  rwp.player_id,
  rwp.player_name,
  rwp.player_points,
  rwp.shots_taken,
  coalesce(tt.team_points, rwp.player_points) as team_points
from roster_with_points rwp
left join team_totals tt
  on tt.season_id = rwp.season_id and coalesce(tt.season_team_id, -1) = coalesce(rwp.season_team_id, -1);

grant select on v_active_scoreboard_rows to public;

enable row level security on seasons;
enable row level security on season_teams;
enable row level security on season_roster;
enable row level security on players;
enable row level security on tiers;
enable row level security on shot_events;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'seasons' and policyname = 'seasons_select_all'
  ) then
    create policy seasons_select_all on seasons for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'season_teams' and policyname = 'season_teams_select_all'
  ) then
    create policy season_teams_select_all on season_teams for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'season_roster' and policyname = 'season_roster_select_all'
  ) then
    create policy season_roster_select_all on season_roster for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'players' and policyname = 'players_select_all'
  ) then
    create policy players_select_all on players for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'tiers' and policyname = 'tiers_select_all'
  ) then
    create policy tiers_select_all on tiers for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'shot_events' and policyname = 'shot_events_select_all'
  ) then
    create policy shot_events_select_all on shot_events for select using (true);
  end if;

  if exists (
    select 1 from pg_policies where tablename = 'shot_events' and policyname = 'shot_events_insert_admin'
  ) then
    drop policy shot_events_insert_admin on shot_events;
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'shot_events' and policyname = 'shot_events_insert_all'
  ) then
    create policy shot_events_insert_all on shot_events for insert with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'shot_events' and policyname = 'shot_events_update_admin'
  ) then
    create policy shot_events_update_admin on shot_events for update using (is_admin());
  end if;
end;
$$;
